### PR TITLE
feat: add dark theme and theme toggle button

### PR DESCRIPTION
**Pull request by arpanaditya**
Solved #2 
- Add a dark theme
- Add theme switch button for both mobile and web

### CODE REVIEW

**Comment by arpanaditya** [comment]
Hey @sainanda59 , I have done the required changes and created this PR, Please go through the codes and accept and do merge the PR with the appropriate label. Lemme know if you have any issues. 🚀 👍

**Comment by sainanda59** [comment]
@arpanaditya Great work, Buddy! Looks amazing

**Comment by arpanaditya** [comment]
Thank you :)

Thank You
Aditya Arpan Sahoo
Cell: 8763012773
Mail to: ***@***.***

**Comment by arpanaditya** [comment]
Thank you :)

**Pull request merged**
